### ISSUE TITLE
Config typo

### ISSUE THREAD

**Issue by moritztim** [vincentscode/Vimeo-OTT-Downloader#1]
https://github.com/vincentscode/Vimeo-OTT-Downloader/blob/d385141050a48a601e1d4b27102c761df13958bb/README.md?plain=1#L23
Should be `urls` instead of `url`, as the script references:
https://github.com/vincentscode/Vimeo-OTT-Downloader/blob/d385141050a48a601e1d4b27102c761df13958bb/vimeo-ott-downloader.py#L36

**Comment by vincentscode** [comment]
Good catch, thanks!
